apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: danielmoreiradeveloper/projeto-k8s-pipeline-deploy-database:1.0
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
        -   containerPort: 3306
            name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets-k8s
                key: ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: secrets-k8s
                key: MYSQL_DATABASE

        volumeMounts:
        -   name: mysql-dados
            mountPath: /var/lib/mysql/
      volumes:
      - name: mysql-dados
        persistentVolumeClaim:
            claimName: mysql-dados